# Generated by Django 2.2 on 2020-05-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdddress',
            new_name='ShippingAddress',
        ),
    ]
